plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dogra.nethunterguide'
    compileSdk 37

    defaultConfig {
        applicationId "com.dogra.nethunterguide"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
